export const actions = {
  INITIALIZE_LIST: "INITIALIZE_LIST",
  PRICE_HIGH_TO_LOW: "PRICE_HIGH_TO_LOW",
  PRICE_LOW_TO_HIGH: "PRICE_LOW_TO_HIGH",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_TO_SAVE_FOR_LATER: "ADD_TO_SAVE_FOR_LATER",
  REMOVE_FROM_SAVE_FOR_LATER: "REMOVE_FROM_SAVE_FOR_LATER",
  MOVE_FROM_SAVE_FOR_LATER_TO_CART: "MOVE_FROM_SAVE_FOR_LATER_TO_CART",
  UPDATE_CATEGORY_FILTERS: "UPDATE_CATEGORY_FILTERS",
  CLEAR_ALL_FILTERS: "CLEAR_ALL_FILTERS",
  RESET_STATE: "RESET_STATE",
};
