export const actions = {
  INITIALIZE_LIST: "INITIALIZE_LIST",
  PRICE_HIGH_TO_LOW: "PRICE_HIGH_TO_LOW",
  PRICE_LOW_TO_HIGH: "PRICE_LOW_TO_HIGH",
  UPDATE_CATEGORY_FILTERS: "UPDATE_CATEGORY_FILTERS",
  CLEAR_ALL_FILTERS: "CLEAR_ALL_FILTERS",
  RESET_STATE: "RESET_STATE",
};
